Wrap apply_manifest into RSpec context; initialise litmus earlier
This fixes the following error by exposing the necessary PuppetLitmus context:

```
An error occurred while loading ./spec/acceptance/01_apt_class_spec.rb.
Failure/Error: apply_manifest(lsb_package)
NameError:
  undefined local variable or method `os' for main:Object
# ./vendor/bundle/ruby/2.5.0/gems/puppet_litmus-0.22.0/lib/puppet_litmus/puppet_helpers.rb:86:in `block in apply_manifest'
# ./vendor/bundle/ruby/2.5.0/gems/honeycomb-beeline-2.4.0/lib/honeycomb/client.rb:70:in `start_span'
# ./vendor/bundle/ruby/2.5.0/gems/puppet_litmus-0.22.0/lib/puppet_litmus/puppet_helpers.rb:41:in `apply_manifest'
# ./spec/spec_helper_acceptance_local.rb:17:in `<top (required)>'
# ./spec/spec_helper_acceptance.rb:4:in `require'
# ./spec/spec_helper_acceptance.rb:4:in `<top (required)>'
# ./spec/acceptance/01_apt_class_spec.rb:3:in `require'
# ./spec/acceptance/01_apt_class_spec.rb:3:in `<top (required)>'
```